apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
template:
  metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: voting-app
    
spec:
  containers: 
  - name: postgres
    image: postgres:9.4
    ports:
    - containerPort: 5432
