apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: voting-app
    spec:
      containers: 
      - name: result-app
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
    
